apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb
    spec:
      containers:
      - image: docker.io/sankethipparge/php-mariadb:mariadb
        name: php-mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "unnati"
        - name: MYSQL_USER
          value: "sanket"
        - name: MYSQL_PASSWORD
          value: "redhat"
        resources: {}
status: {}
