
FROM php:8.2-apache

RUN docker-php-ext-install mysqli

RUN a2enmod rewrite

COPY . /var/www/html/

WORKDIR /var/www/html/

ENV DB_HOST=mariadb \
    DB_USER=web_user \
    DB_PASS=secure_password \
    DB_NAME=my_database

